import Vue from 'vue'
import Router from 'vue-router'


Vue.use(Router)

export default new Router({
  routes: [
    {
      path:'/',
      redirect:'/index'
    },  
    {
      path:'/index',
      component:()=>import('../components/index.vue'),
      meta:{title:'登录页'}
    },
    {
      path:'/dufalt',
      component:()=>import('../components/dufalt.vue'),
      meta:{title:'70点货'},
      children:[
        {
          path:'/home',
          component:()=>import('../components/pages/home.vue'),
          meta:{title:'首页'}
        }, 
        {
          path:'/person',
          component:()=>import('../components/pages/person.vue'),
          meta:{title:'个人中心'}
        },
        {
          path:'/aeproduct',
          component:()=>import('../components/pages/aeproduct.vue'),
          meta:{title:'添加产品'}
        },
        {
          path:'/productlist',
          component:()=>import('../components/pages/productlist.vue'),
          meta:{title:'产品管理'}
        },
        {
           
             path:'/shoppingcart',
             component:()=>import('../components/pages/shoppingcart.vue'),
             meta:{title:'购物车'}
           
        },
        {
          path:'/order',
          component:()=>import('../components/pages/order.vue'),
          meta:{title:'订单'}
        },
        {
          path:'/orderdetail',
          component:()=>import('../components/pages/orderdetail.vue'),
          meta:{title:'订单详情'}
        },
        {
          path:'/shops',
          component:()=>import('../components/pages/shops.vue'),
          meta:{title:'商店列表'}
        },
        {
          path:'/shopproduct',
          component:()=>import('../components/pages/shopproduct.vue'),
          meta:{title:'商品列表'}
        },
        {
          path:'/userreg',
          component:()=>import('../components/pages/userreg.vue'),
          meta:{title:"用户注册"}
        },
        {
          path:'/shoporder',
          component:()=>import('../components/pages/shoporder.vue'),
          meta:{title:'商店订单'}
        },
        {
          path:'/myshop',
          component:()=>import('../components/pages/myshop.vue'),
          meta:{title:'创建店铺'}
        },
        {
          path:'/seller',
          component:()=>import('../components/pages/seller.vue'),
          meta:{title:"商家区域"}
        },
        {
          path:'/editproduct',
          component:()=>import('../components/pages/editproduct.vue'),
          meta:{title:'商品编辑'}
        },
        {
          path:'/about',
          component:()=>import('../components/pages/about.vue'),
          meta:{title:'关于'}
        },
        {
          path:'/shopAdmin',
          component:()=>import('../components/admin/shopsAdmin.vue'),
          meta:{title:'管理店铺'}
        },
        {
          path:'/sumproduct',
          component:()=>import('../components/pages/sumproduct.vue'),
          meta:{title:'产品拍照统计'}
        },
        {
          path:'/statistics',
          component:()=>import('../components/pages/Statistics.vue'),
          meta:{title:'销售统计'},
        },
        {
          path:'/sumbymonth',
          component:()=>import('../components/pages/SumByMonth.vue'),
          meta:{title:'每月销售统计'}
        },
        {
          path:'/adminpage',
          component:()=>import('../components/admin/adminpage.vue'),
          meta:{title:'店铺管理'}
        },
        {
          path:'/kindsadmin',
          component:()=>import('../components/admin/kindsadmin.vue'),
          meta:{title:'行业分类'}
        },
        {
          path:'/protype',
          component:()=>import('../components/admin/protype.vue'),
          meta:{title:'产品分类'}
        },
        {
          path:'/custmoter',
          component:()=>import('../components/admin/custmoter.vue'),
          meta:{title:'我是买家'}
        },
        {
          path:'/address',
          component:()=>import('../components/admin/address.vue'),
          meta:{title:'收货地址'}
        },
        {
          path:'/editaddress',
          component:()=>import('../components/admin/editaddress.vue'),
          meta:{title:'编辑收货地址'}
        },
        {
          path:'/clientage',
          component:()=>import('../components/admin/clientage.vue'),
          meta:{title:'客户群'}
        },
        {
          path:'/showqrcode',
          component:()=>import('../components/pages/showqrcode.vue'),
          meta:{title:'店铺二维码'}
        }
      ]
    }
  ]
})

